import "./globals.css";
export const metadata = {
  title: "Hello .js",
  description: "Generated by Next.js",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>{children}g</header>
      </body>
    </html>
  );
}
