import Card from "../components/cards";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  users,
  notifications,
  login,
  about,
}: {
  children: React.ReactNode;
  users: React.ReactNode;
  notifications: React.ReactNode;
  about: React.ReactNode;
  login: React.ReactNode;
}) {
  const isLogin = false;
  return (
    <html lang="en">
      <body>
        {children}
        {isLogin ? (
          <div>
            <h1>{children}</h1>
            <div style={{ display: "flex" }}>
              <div style={{ display: "flex", flexDirection: "column" }}>
                <div>{users}</div>
                <div>{about}</div>
              </div>
              <div style={{ display: "flex", flex: 1 }}>{notifications}</div>
            </div>
          </div>
        ) : (
          <Card >{login}</Card>
        )}{" "}
      </body>
    </html>
  );
}
