export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  users,
  notifications,
  about,
}: {
  children: React.ReactNode;
  users: React.ReactNode;
  notifications: React.ReactNode;
  about: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <div>
          <h1>{children}</h1>
          <div style={{ display: "flex" }}>
            <div style={{ display: "flex", flexDirection: "column" }}>
              <div>{users}</div>
              <div>{about}</div>
            </div>
            <div style={{ display: "flex", flex: 1 }}>{notifications}</div>
          </div>
        </div>{" "}
      </body>
    </html>
  );
}
